default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  adapter: postgresql

test:
  <<: *default
  adapter: postgresql

production:
  <<: *default
  adapter: postgresql
